# Set the Monokai colorscheme hex codes
MONOKAI_RED="#F92672"
export MONOKAI_RED

MONOKAI_BLUE="#66D9EF"
export MONOKAI_BLUE

MONOKAI_GREEN="#A6E22E"
export MONOKAI_GREEN

MONOKAI_PURPLE="#AE81FF"
export MONOKAI_PURPLE

MONOKAI_YELLOW="#E6DB74"
export MONOKAI_YELLOW

MONOKAI_ORANGE="#FD971F"
export MONOKAI_ORANGE

MONOKAI_BG="#212121"
export MONOKAI_BG
